# Generated by Django 4.2.4 on 2024-01-22 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['address_name']},
        ),
        migrations.AlterField(
            model_name='address',
            name='mini_map',
            field=models.FileField(blank=True, null=True, upload_to='address_static_maps/'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user', 'address_name')},
        ),
    ]
