# Generated by Django 4.2.4 on 2023-11-19 16:11

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import offers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='max 120 characters', max_length=120, unique=True)),
                ('name_ua', models.CharField(max_length=120, null=True)),
                ('group', models.CharField(max_length=60, null=True)),
            ],
            options={
                'ordering': ['group', 'category_name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_offer', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('terms_delivery', models.CharField(help_text='for example, FCA', max_length=3, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('expired_at', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=18, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=18, null=True)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry_point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('mini_map_img', models.FileField(null=True, storage=offers.models.select_storages, upload_to='offer_static_maps')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='offers.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
