# Generated by Django 4.2.4 on 2024-01-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='mini_map_img',
            field=models.FileField(blank=True, null=True, upload_to='offer_static_maps'),
        ),
    ]
