# Generated by Django 4.2.4 on 2024-01-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
