# Generated by Django 4.2.4 on 2024-01-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('offers_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'actual_countries',
                'ordering': ['name'],
            },
        ),
    ]
