# Generated by Django 4.2.4 on 2023-11-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={"ordering": ["-created_at", "category"]},
        ),
        migrations.AlterField(
            model_name="offer",
            name="address",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="details",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=16, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=16, max_digits=18, null=True
            ),
        ),
    ]
