# Generated by Django 4.2.4 on 2024-01-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_actualcountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualcountry',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
