# Generated by Django 4.2.4 on 2023-11-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offer_latitude_alter_offer_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
