# Generated by Django 4.2.4 on 2023-11-07 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0003_remove_offer_author_addressdelivery_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="measurement",
        ),
    ]
