# Generated by Django 4.2.4 on 2023-11-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0004_remove_offer_measurement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addressdelivery",
            name="address_name",
        ),
        migrations.RemoveField(
            model_name="addressdelivery",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="addressdelivery",
            name="lng",
        ),
        migrations.AddField(
            model_name="offer",
            name="latitude",
            field=models.DecimalField(decimal_places=16, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="longitude",
            field=models.DecimalField(decimal_places=16, max_digits=18, null=True),
        ),
    ]
