# Generated by Django 4.2.4 on 2023-11-11 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0005_remove_addressdelivery_address_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="currency",
        ),
    ]
