# Generated by Django 4.2.4 on 2023-11-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0006_remove_offer_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
            preserve_default=False,
        ),
    ]
