# Generated by Django 4.2.4 on 2023-11-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0007_offer_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="title",
        ),
        migrations.AddField(
            model_name="offer",
            name="details",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
