# Generated by Django 4.2.4 on 2023-11-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0008_remove_offer_title_offer_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.AddField(
            model_name="category",
            name="name_ua",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
