CATEGORIES = [
    "Rye flour",
    "Oat flour",
    "Vetch",
    "Wheat mill offal's",
    "Mustard seeds",
    "Peas",
    "Buckwheat",
    "Rye",
    "Rye grade II",
    "Rye grade III",
    "Rye grade IV",
    "Sugar beet pulp gran",
    "Green peas",
    "Coriander",
    "Buckwheat groats",
    "Corn",
    "Linseed oil",
    "Soybean hulls granulated",
    "Flax",
    "Lupine",
    "Poppy seeds",
    "Rape-seed cake",
    "Soybean cake",
    "Sunflower oil cake",
    "Beet molasses",
    "Wheat flour, class 1",
    "Wheat flour, extra class",
    "Chick-peas",
    "Oats",
    "Corn oil",
    "Rape-seed oil",
    "Sunflower- oil",
    "Monogram wheat",
    "Millet",
    "Wheat, grade I",
    "Wheat grade II",
    "Wheat grade III",
    "Wheat grade IV",
    "Wheat grade V",
    "Wheat grade VI",
    "Rapeseed 1 grade less 35mcm",
    "Rapeseed 2 grade more 35mcm",
    "Rapeseed high grade less 25mcm",
    "GM rape",
    "Rice",
    "Thistle ",
    "Soybean oil",
    "Soybean phosphate concentrate",
    "Sunflower",
    "Sunflower high-oil",
    "Confectionery sunflower seeds",
    "Sorghum white",
    "Sorghum red",
    "Soybeans",
    "Soybeans GMO-free",
    "Spelt wheat",
    "Triticale",
    "Sugar",
    "Lentil",
    "Rape-seed coarse meal",
    "Soybean meal",
    "Sunflower seed meal",
    "Barley",
    "Malting barley",
]