# -*- coding: utf-8 -*-

CATEGORIES = [
    "Barley",
    "Beet molasses",
    "Buckwheat",
    "Chick-peas",
    "Coriander",
    "Corn",
    "Corn oil",
    "Flax",
    "Green peas",
    "Lentil",
    "Linseed oil",
    "Lupine",
    "Millet",
    "Mustard seeds",
    "Oat flour",
    "Oats",
    "Peas",
    "Poppy",
    "Rape-seed cake",
    "Rape-seed meal",
    "Rape-seed oil",
    "Rapes-eed",
    "Rice",
    "Rye",
    "Rye flour",
    "Rye grade 2",
    "Rye grade 3",
    "Rye grade 4",
    "Sorghum",
    "Soybean cake",
    "Soybean meal",
    "Soybean oil",
    "Soybeans",
    "Sugar",
    "Sugar beet pulp gran",
    "Sunflower",
    "Sunflower oil",
    "Sunflower oil cake",
    "Sunflower seed meal",
    "Triticale",
    "Vetch",
    "Wheat flour class 1",
    "Wheat flour extra class",
    "Wheat grade 1",
    "Wheat grade 2",
    "Wheat grade 3",
    "Wheat grade 4",
    "Wheat grade 5",
    "Wheat grade 6",
]

CATEGORIES_UA = [
    "Ячмінь",
    "Меляса бурякова",
    "Гречка",
    "Нут",
    "Коріандр",
    "Кукурудза",
    "Кукурудзяна олія",
    "Льон",
    "Зелений горошок",
    "Сочевиця",
    "Лляна олія",
    "Люпин",
    "Пшоно",
    "Зерна гірчиці",
    "Вівсяне борошно",
    "Овес",
    "Горох",
    "Мак",
    "Ріпаковий макуха",
    "Ріпаковий шрот",
    "Ріпакова олія",
    "Рапс",
    "Рис",
    "Жито",
    "Житнє борошно",
    "Жито 2 сорт",
    "Жито 3 сорт",
    "Жито 4 сорт",
    "Сорго",
    "Соєвий макуха",
    "Соєвий шрот",
    "Олія соєва",
    "Соєві боби",
    "Цукор",
    "Жом цукрових буряків гран",
    "Соняшник",
    "Соняшникова олія",
    "Макуха соняшникова",
    "Шрот соняшниковий",
    "Тритикале",
    "Віка",
    "Борошно пшеничне 1 класу",
    "Борошно пшеничне вищого сорту",
    "Пшениця 1 сорт",
    "Пшениця 2 сорт",
    "Пшениця 3 сорт",
    "Пшениця 4 сорт",
    "Пшениця 5 сорт",
    "Пшениця 6 сорт",
]

zipped = {
    "Barley": "Ячмінь",
    "Beet molasses": "Меляса бурякова",
    "Buckwheat": "Гречка",
    "Chick-peas": "Нут",
    "Coriander": "Коріандр",
    "Corn": "Кукурудза",
    "Corn oil": "Кукурудзяна олія",
    "Flax": "Льон",
    "Green peas": "Зелений горошок",
    "Lentil": "Сочевиця",
    "Linseed oil": "Лляна олія",
    "Lupine": "Люпин",
    "Millet": "Пшоно",
    "Mustard seeds": "Зерна гірчиці",
    "Oat flour": "Вівсяне борошно",
    "Oats": "Овес",
    "Peas": "Горох",
    "Poppy": "Мак",
    "Rape-seed cake": "Ріпаковий макуха",
    "Rape-seed meal": "Ріпаковий шрот",
    "Rape-seed oil": "Ріпакова олія",
    "Rapes-eed": "Рапс",
    "Rice": "Рис",
    "Rye": "Жито",
    "Rye flour": "Житнє борошно",
    "Rye grade 2": "Жито 2 сорт",
    "Rye grade 3": "Жито 3 сорт",
    "Rye grade 4": "Жито 4 сорт",
    "Sorghum": "Сорго",
    "Soybean cake": "Соєвий макуха",
    "Soybean meal": "Соєвий шрот",
    "Soybean oil": "Олія соєва",
    "Soybeans": "Соєві боби",
    "Sugar": "Цукор",
    "Sugar beet pulp gran": "Жом цукрових буряків гран",
    "Sunflower": "Соняшник",
    "Sunflower oil": "Соняшникова олія",
    "Sunflower oil cake": "Макуха соняшникова",
    "Sunflower seed meal": "Шрот соняшниковий",
    "Triticale": "Тритикале",
    "Vetch": "Віка",
    "Wheat flour class 1": "Борошно пшеничне 1 класу",
    "Wheat flour extra class": "Борошно пшеничне вищого сорту",
    "Wheat grade 1": "Пшениця 1 сорт",
    "Wheat grade 2": "Пшениця 2 сорт",
    "Wheat grade 3": "Пшениця 3 сорт",
    "Wheat grade 4": "Пшениця 4 сорт",
    "Wheat grade 5": "Пшениця 5 сорт",
    "Wheat grade 6": "Пшениця 6 сорт",
}
